### ISSUE TITLE
[Integration] CLI-Guide.JS for Scala School

### ISSUE THREAD

**Issue by marti1125** [twitter/scala_school#155]
Hi! I am working in jquery plugin is a javascript library for creating interactive command line tutorials that run in your web browser.
http://twitter.github.io/cli-guide.js/
Demo: http://twitter.github.io/cli-guide.js/demo/aurora.html
I hope we can work together ^_^

**Comment by benpence** [comment]
This is not the correct repository. Please post this issue here: https://github.com/twitter/cli-guide.js/issues .
