### ISSUE TITLE
Methods vs functions on Basics page

### ISSUE THREAD

**Issue by masaeedu** [twitter/scala_school#156]
On the [Basics page](https://twitter.github.io/scala_school/basics.html), we have this section:

> # Functions
> 
> You can create functions with def.
> 
> ```
> scala> def addOne(m: Int): Int = m + 1
> addOne: (m: Int)Int
> ```
> 
> ...
> 
> You can leave off parens on functions with no arguments.
> 
> ```
> scala> def three() = 1 + 2
> three: ()Int
> 
> scala> three()
> res2: Int = 3
> 
> scala> three
> res3: Int = 3
> ```

Perhaps this could be titled "Methods", and refer to methods instead of functions? You can leave off parens on methods with no arguments, but you can't leave off parens on functions with no arguments. E.g. this will not evaluate the function:

```
scala> val f = () => 1
f: () => Int = <function0>

scala> f
res19: () => Int = <function0>
```

The aside further down is helpful, but it seems to take the approach that the difference between functions and methods is very complicated and is best left to language experts. This doesn't necessarily need to be the case (IMO), and a brief explanation of the following shouldn't be too terrifying:
1. Functions are objects
   
   ```
   val threeFunction = () => 1 + 2
   ```
2. Methods are not functions (and hence not objects)
   
   ```
   def threeMethod: Int = 1 + 2
   ```
3. This is okay, because in most cases, a method is automatically wrapped in a new function if you try to treat it as one
   
   ```
   val threeFunction = threeMethod
   ```

**Comment by benpence** [comment]
Pull requests are a much better medium to talk about how the code should change. Please feel free to submit one.
