### ISSUE TITLE
GitHub removing textile support

### ISSUE THREAD

**Issue by alanmbarr** [twitter/scala_school#167]
https://github.com/blog/2115-upgrading-your-textile-posts-to-markdown

Do you want help converting these documents to markdown?  It looks like your site won't render after May 1st. I was looking into making these documents responsive and noticed this might be an issue for this soon?

**Comment by lahosken** [comment]
Sweet offer! IIUC, the site should be OK. Instead of using github's textile support (I didn't even know that was a thing), folks generate .html on their laptops and publish that. https://github.com/twitter/scala_school/tree/gh-pages .

**Comment by benpence** [comment]
I'm closing this since @alanmbarr did not respond.

We would love to have these pages converted to Markdown. Please send a pull request if you do. Thanks!
