### ISSUE TITLE
The site is broken (all the requests to get the css files get 404)

### ISSUE THREAD

**Issue by Kevin-Lee** [twitter/scala_school#213]
This is what Scala school looks like right now.
![screen shot 2018-10-30 at 3 27 17 am](https://user-images.githubusercontent.com/2307335/47664900-18d64980-dbf4-11e8-9287-e4a50308f30f.png)

As you can see, accessing the css files get only 404.

**Comment by Kevin-Lee** [comment]
I think #211 should fix this issue but why do I still see that broken page? 🤔

**Comment by Kevin-Lee** [comment]
I guess the latest one hasn't been deployed yet. Can we have it deployed?

**Comment by kell18** [comment]
Any news?

**Comment by jarvisgroup** [comment]
+1

**Comment by franklingu** [comment]
this issue seems to to take long enough to fix it

**Comment by Kevin-Lee** [comment]
I was fixed two months ago but not released not. I think Twitter needs some DevOps.

**Comment by Kevin-Lee** [comment]
It was fixed two months ago but not released not. I think Twitter needs some DevOps.

**Comment by Kevin-Lee** [comment]
Since it looks like it would take forever to deploy it, I forked it and did it myself. 
Until it's fixed by Twitter, we can use https://kevin-lee.github.io/scala_school/

**Comment by rafaelmagu** [comment]
Paging @kevinoliver as someone associated with the Twitter organization here on GitHub. Can you help us find a maintainer for this repo to deploy the merged changes?

**Comment by kevinoliver** [comment]
@rafaelmagu I've asked some folks over here to take a look.

**Comment by Kevin-Lee** [comment]
I can see it working so I'm closing this issue.
